AutoUpdater
MatrikMoon/TournamentAssistant pull request #14
Opened 2021-03-12 12:08 UTC by Arimodu

2021-03-27 20:21 UTC, MatrikMoon commented
Marking as closed per your request

2021-03-27 20:23 UTC, MatrikMoon commented
Reopening per our misunderstanding xD

2021-03-27 20:29 UTC, MatrikMoon commented on TournamentAssistantCore/Properties/PublishProfiles/Linux.pubxml
> +    <PublishDir>E:\</PublishDir>
I'm pretty sure you're gonna wanna avoid doing this

2021-03-27 20:30 UTC, MatrikMoon commented on TournamentAssistantCore/TournamentAssistantCore.csproj.user
> +    <_LastSelectedProfileId>C:\Users\blob\Source\Repos\TournamentAssistant\TournamentAssistantCore\Properties\PublishProfiles\Linux.pubxml</_LastSelectedProfileId>
I don't think either of these lines is right xD
I probably should change this so something either dynamic or generic

2021-03-27 21:40 UTC, Arimodu commented on TournamentAssistantCore/Properties/PublishProfiles/Linux.pubxml
> +    <PublishDir>E:\</PublishDir>
I will avoid it. I had changed it because I compiled it on a VM with broken .NET so I had to compile and start outside of VM.

2021-03-27 22:52 UTC, Arimodu commented
Ok so I made the actual 4 line script, this **should** fix the issue on linux.
Script is in a repo here: https://raw.githubusercontent.com/Arimodu/TAUpdateScript/main/Update.sh

2021-03-27 22:53 UTC, Arimodu commented on TournamentAssistantCore/Properties/PublishProfiles/Linux.pubxml
> +    <PublishDir>E:\</PublishDir>
Fixed it in the PR

2021-04-01 22:46 UTC, MatrikMoon commented
When you say issue on linux, do you mean linux should work now?

2021-04-01 22:49 UTC, MatrikMoon commented on TournamentAssistantCore/TournamentAssistantCore.csproj.user
> -    <_LastSelectedProfileId>C:\Users\Moon\source\repos\TournamentAssistant\TournamentAssistantCore\Properties\PublishProfiles\Docker.pubxml</_LastSelectedProfileId>
Can we just unstage this file? Honestly I'm scared to touch it xD

2021-04-01 22:51 UTC, MatrikMoon requested changes
Not much left to resolve here, aside from my own curiosity. I look forward to rolling this out!

2021-04-01 22:51 UTC, MatrikMoon commented on TournamentAssistantCore/TournamentAssistantCore.csproj.user
> -    <_LastSelectedProfileId>C:\Users\Moon\source\repos\TournamentAssistant\TournamentAssistantCore\Properties\PublishProfiles\Docker.pubxml</_LastSelectedProfileId>
Can we just unstage this file? Honestly I'm scared to touch it xD

2021-04-01 22:51 UTC, MatrikMoon commented on Shared/Update.cs
> +        public static void PollForUpdates(Action doAfterUpdate, CancellationToken cancellationToken)
Just for my own curiosity, what actually uses doAfterupdate now that we have an auto-updater?

2021-04-02 07:07 UTC, Arimodu commented on Shared/Update.cs
> +        public static void PollForUpdates(Action doAfterUpdate, CancellationToken cancellationToken)
I reused it to shutdown the server, there is a possibility that it might fail (maybe you change the name of the exec), in that case, we still need to shut the server down.

2021-04-02 07:09 UTC, Arimodu commented on TournamentAssistantCore/TournamentAssistantCore.csproj.user
> -    <_LastSelectedProfileId>C:\Users\Moon\source\repos\TournamentAssistant\TournamentAssistantCore\Properties\PublishProfiles\Docker.pubxml</_LastSelectedProfileId>
well technically any csproj.user files SHOULD be in gitignore, well anyway ill unstage it and add it to gitignore

2021-06-16 01:03 UTC, MatrikMoon approved these changes
I deem you... WORTHY

2021-06-16 01:03 UTC, merged