Proto websocket fixes & support for server client messages
MatrikMoon/TournamentAssistant pull request #41
Opened 2022-05-04 13:26 UTC by Dannypoke03

2022-05-05 12:58 UTC, MatrikMoon requested changes
Lookin good! Just a quick comment or two and we'll get 'er merged in

2022-05-05 12:58 UTC, MatrikMoon commented on TournamentAssistant/UI/FlowCoordinators/FlowCoordinatorWithClient.cs
> -            if (Plugin.client?.Connected == false) await Plugin.client.Start();
Is there any reason we're not awaiting this anymore? I put a lot of thought into those during the async rewrite, and now that I'm being told it's more stable than ever, I'm hesitant to change any of them

2022-05-05 12:58 UTC, MatrikMoon commented on TournamentAssistantShared/SystemClient.cs
> +        public event Action<Message> Message;
It doesn't matter much given what you actually do with it, but if we could make this a Func instead of an Action, if only to be inline with the other events, that'd be nice

2022-05-06 05:49 UTC, Dannypoke03 commented on TournamentAssistant/UI/FlowCoordinators/FlowCoordinatorWithClient.cs
> -            if (Plugin.client?.Connected == false) await Plugin.client.Start();
No reason specifically, it was probably just leftover from merging pre async with new async and it didn't get carried across. Will fix that up shortly.

2022-05-06 05:50 UTC, Dannypoke03 commented on TournamentAssistantShared/SystemClient.cs
> +        public event Action<Message> Message;
Similar to the above issue, just a case of merging pre async rewrite code with the new async code. Will fix it up shortly.

2022-05-06 17:38 UTC, MatrikMoon approved these changes
Just the one comment, but it's good enough to merge for now. Well played!

2022-05-06 17:38 UTC, MatrikMoon commented on TournamentAssistantCore/SystemServer.cs
> +                await BroadcastToAllClients(packet, false);
This is good enough for now, but I get the feeling not _all_ players and coordinators and panels need to know about this. I may be guilty of overusing this as well. Remind me to revisit this and the stream sync code to be sure messages aren't going places they don't need to be in the future

2022-05-06 17:38 UTC, merged